let shopItemsData = [
    {
        id: "1",
        name: "Broken Heart",
        price: "60",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "images/1.jpg",
    },
    {
        id: "2",
        name: "Broken Heart",
        price: "60",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "images/2.jpg",
    },
    {
        id: "3",
        name: "Broken Heart",
        price: "60",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "images/3.jpg",
    },
    {
        id: "4",
        name: "Broken Heart",
        price: "60",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "images/4.jpg",
    },
    {
        id: "5",
        name: "Broken Heart",
        price: "60",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "images/5.jpg",
    },
    {
        id: "6",
        name: "Broken Heart",
        price: "60",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "images/6.jpg",
    },
    {
        id: "7",
        name: "Broken Heart",
        price: "60",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "images/7.jpg",
    },
    {
        id: "8",
        name: "Broken Heart",
        price: "60",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "images/8.jpg",
    },
];